mysite/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    #myapp_url
    re_path(r'^', include('tracer.urls')),
    re_path(r'^api/', include('detector.urls'))


]

tracer/urls.py
from django.views.static import serve
from tracer.views import account, file, setting, issues, project_detail, statistics, navigation
from tracer.views import project
from tracer.views import wiki

from rest_framework.routers import DefaultRouter
from django.urls import path, re_path, include
from mysite import settings
from tracer.views import mock_scene

router = DefaultRouter()
router.register("scene", mock_scene.SceneInfoViewSet, basename="scene")

urlpatterns = [
    path('bytedance/', account.bytedance_login, name='bytedance_login'),
    path('register/', account.register, name='register'),
    path('register_valid_code/', account.register_valid_code),
    path('login/', account.login, name='login'),
    path('login/sms/', account.login_sms, name='login_sms'),
    path('get_validCode_img/', account.get_validCode_img, name='image_code'),
    path('index/', account.index, name='index'),
    re_path('^$', account.index),
    path('logout/', account.logout, name='logout'),
    re_path(r"media/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT}),
    # path('upload/', account.upload),
    #项目列表
    path('project/list/', project.project_list, name='project_list'),
    re_path(r'^project/list/application/(?P<project_id>\d+)/$', project.project_application, name='project_application'),

    re_path(r'^project/unstar/(?P<project_type>\w+)/(?P<project_id>\d+)/$', project.project_unstar, name='project_unstar'),
    re_path(r'^project/star/(?P<project_type>\w+)/(?P<project_id>\d+)/$', project.project_star, name='project_star'),

    #项目管理
    re_path(r'^manage/(?P<project_id>\d+)/', include([
        re_path(r'^wiki/$', wiki.wiki, name='wiki'),
        re_path(r'^wiki/add/$', wiki.wiki_add, name='wiki_add'),
        re_path(r'^wiki/catalog/$', wiki.wiki_catalog, name='wiki_catalog'),
        # re_path(r'^wiki/sub/catalog/(?P<wiki_id>\d+)/$', wiki.wiki_sub_catalog, name='wiki_sub_catalog'),
        re_path(r'^wiki/delete/(?P<wiki_id>\d+)/$', wiki.wiki_delete, name='wiki_delete'),
        re_path(r'^wiki/edit/(?P<wiki_id>\d+)/$', wiki.wiki_edit, name='wiki_edit'),
        re_path(r'^wiki/upload/$', wiki.wiki_upload, name='wiki_upload'),

        re_path(r'^file/$', file.file, name='file'),
        re_path(r'^file/delete/$', file.file_delete, name='file_delete'),
        re_path(r'^cos/credential/$', file.cos_credential, name='cos_credential'),
        re_path(r'^file/post/$', file.file_post, name='file_post'),
        re_path(r'^file/download/(?P<file_id>\d+)/$', file.file_download, name='file_download'),

        re_path(r'^setting/$', setting.setting, name='setting'),
        re_path(r'^setting/issue/type/$', setting.add_issuetype, name='add_issue_type'),
        re_path(r'^setting/issue/type/delete/$', setting.delete_issuetype, name='delete_issuetype'),
        re_path(r'^setting/app/require/$', setting.app_require, name='app_require'),
        re_path(r'^setting/app/require/delete/$', setting.delete_app_require, name='delete_app_require'),
        re_path(r'^setting/debug/$', setting.debug, name='debug'),
        re_path(r'^setting/delete/$', setting.delete, name='setting_delete'),

        re_path(r'^issues/$', issues.issues, name='issues'),
        re_path(r'^issues/detail/(?P<issues_id>\d+)/$', issues.issues_detail, name='issues_detail'),
        re_path(r'^issues/record/(?P<issues_id>\d+)/$', issues.issues_record, name='issues_record'),
        re_path(r'^issues/change/(?P<issues_id>\d+)/$', issues.issues_change, name='issues_change'),
        re_path(r'^issues/invite/url/$', issues.invite_url, name='invite_url'),

        re_path(r'^dashboard/$', project_detail.dashboard, name='dashboard'),
        re_path(r'^project/detail/$', project_detail.project_detail, name='project_detail'),
        re_path(r'^project/mock/scene/$', mock_scene.mock_scene, name='mock_scene'),

        re_path(r'^result/save/$', project_detail.result_save, name='result_save'),
        re_path(r'^result/search/$', project_detail.result_search, name='result_search'),
        re_path(r'^dashboard/issues/chart/$', project_detail.issues_chart, name='issues_chart'),

        re_path(r'^statistics/$', statistics.statistics, name='statistics'),
        re_path(r'^statistics/priority/$', statistics.statistics_priority, name='statistics_priority'),
        re_path(r'^statistics/project/user/$', statistics.statistics_project_user, name='statistics_project_user'),

    ], None)),
    re_path(r'^invite/join/(?P<code>\w+)/$', issues.invite_join, name='invite_join'),
    re_path(r'navigation/$', navigation.list_jump, name='list_jump'),

] + router.urls

tracer/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class UserInfo(AbstractUser):
    '''
    user message
    '''
    telephone = models.CharField(max_length=11, null=False, unique=True, default="null")
    avatar = models.FileField(upload_to='avatars/', default='avatars/default.png')
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    # price_policy = models.ForeignKey(verbose_name='价格策略', to='PricePolicy', to_field='nid', null=False, default=1, on_delete=models.SET_NULL)

    def __str__(self):
        return self.username

class PricePolicy(models.Model):
    """ 价格策略 """
    category_choices = (
        (1, '免费版'),
        (2, '收费版'),
        (3, '其他'),
    )
    category = models.SmallIntegerField(verbose_name='收费类型', default=2, choices=category_choices)
    title = models.CharField(verbose_name='标题', max_length=32)
    price = models.PositiveIntegerField(verbose_name='价格')  # 正整数

    project_num = models.PositiveIntegerField(verbose_name='项目数')
    project_member = models.PositiveIntegerField(verbose_name='项目成员数')
    project_space = models.PositiveIntegerField(verbose_name='单项目空间', help_text='G')
    per_file_size = models.PositiveIntegerField(verbose_name='单文件大小', help_text="M")

    create_datetime = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)


    def __str__(self):
        return self.title

class Transaction(models.Model):
    """ 交易记录 """
    status_choice = (
        (1, '未支付'),
        (2, '已支付')
    )
    status = models.SmallIntegerField(verbose_name='状态', choices=status_choice)

    order = models.CharField(verbose_name='订单号', max_length=64, unique=True)  # 唯一索引

    user = models.ForeignKey(verbose_name='用户', to='UserInfo', on_delete=models.CASCADE)
    price_policy = models.ForeignKey(verbose_name='价格策略', to='PricePolicy', on_delete=models.CASCADE)

    count = models.IntegerField(verbose_name='数量（年）', help_text='0表示无限期')

    price = models.IntegerField(verbose_name='实际支付价格')

    start_datetime = models.DateTimeField(verbose_name='开始时间', null=True, blank=True)
    end_datetime = models.DateTimeField(verbose_name='结束时间', null=True, blank=True)

    create_datetime = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)


class Project(models.Model):
    """ 项目表 """
    COLOR_CHOICES = (
        (1, "#56b8eb"),  # 56b8eb
        (2, "#f28033"),  # f28033
        (3, "#ebc656"),  # ebc656
        (4, "#a2d148"),  # a2d148
        (5, "#20BFA4"),  # #20BFA4
        (6, "#7461c2"),  # 7461c2,
        (7, "#20bfa3"),  # 20bfa3,
    )

    name = models.CharField(verbose_name='项目名', max_length=32)
    color = models.SmallIntegerField(verbose_name='颜色', choices=COLOR_CHOICES, default=1)
    desc = models.CharField(verbose_name='项目描述', max_length=255, null=True, blank=True)

    use_space = models.BigIntegerField(verbose_name='项目已使用空间', default=0, help_text='字节')

    star = models.BooleanField(verbose_name='星标', default=False)

    join_count = models.SmallIntegerField(verbose_name='参与人数', default=1)
    creator = models.ForeignKey(verbose_name='创建者', to='UserInfo', null=True, on_delete=models.SET_NULL)
    create_datetime = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)

    bucket = models.CharField(verbose_name='cos桶', max_length=128)
    region = models.CharField(verbose_name='cos区域', max_length=32)
    def __str__(self):
        return self.name

class ProjectUser(models.Model):
    """ 项目参与者 """
    project = models.ForeignKey(verbose_name='项目', to='Project', on_delete=models.CASCADE)
    user = models.ForeignKey(verbose_name='参与者', to='UserInfo', on_delete=models.CASCADE)
    star = models.BooleanField(verbose_name='星标', default=False)

    create_datetime = models.DateTimeField(verbose_name='加入时间', auto_now_add=True)

    def __str__(self):
        v = self.project.name + "---" + self.user.username
        return v

class Wiki(models.Model):
    """Wiki"""
    project = models.ForeignKey(verbose_name='项目', to=Project, on_delete=models.CASCADE)
    title = models.CharField(verbose_name='标题', max_length=32)
    content = models.TextField(verbose_name='内容')
    user = models.ForeignKey(verbose_name='创建者', to=UserInfo, null=True, on_delete=models.SET_NULL)
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    last_edit_time = models.DateTimeField(verbose_name='最近修改时间', null=True, blank=True)
    last_edit_user = models.ForeignKey(verbose_name='最近修改人', to=UserInfo, null=True, blank=True, on_delete=models.SET_NULL, related_name='last_edit_user')
    depth = models.SmallIntegerField(verbose_name='深度', default=1)
    #自关联
    parent = models.ForeignKey(verbose_name='父文章', to='Wiki', null=True, blank=True, on_delete=models.CASCADE, related_name='children')

    def __str__(self):
        return self.title


class WikiJoin(models.Model):
    wiki = models.ForeignKey(verbose_name='wiki', to=Wiki, on_delete=models.CASCADE)
    user = models.ForeignKey(verbose_name='参与者', to=UserInfo, on_delete=models.CASCADE)
    collection = models.BooleanField(verbose_name='收藏', default=False)
    editor = models.BooleanField(verbose_name='编辑', default=False)



class TikTokAutoTest(models.Model):
    platform_choice = (
        (1, 'Android'),
        (2, 'IOS')
    )
    project = models.ForeignKey(verbose_name='项目', to=Project, on_delete=models.CASCADE)
    platform = models.SmallIntegerField(verbose_name='平台', choices=platform_choice)
    version_detail = models.CharField(verbose_name='版本详情', null=True, blank=True, max_length=32)
    task_id = models.IntegerField(verbose_name='任务id')
    test_path = models.CharField(verbose_name='脚本路径', null=True, blank=True, max_length=300)
    event = models.CharField(verbose_name='EVENT', max_length=16)
    test_case_url = models.CharField(verbose_name='埋点url', max_length=300)
    case_id = models.IntegerField(verbose_name='case_id', null=True, blank=True,)
    result = models.BooleanField(verbose_name='测试结果', default=False)
    create_time = models.DateTimeField(verbose_name='收录时间', auto_now_add=True)

    class Meta:
        index_together = ['id', 'create_time']
        ordering = ('-id', '-create_time')
        unique_together = ('task_id', 'case_id')

class FileRepository(models.Model):
    """ 文件库 """
    project = models.ForeignKey(verbose_name='项目', to='Project', on_delete=models.CASCADE)
    file_type_choices = (
        (1, '文件'),
        (2, '文件夹')
    )
    file_type = models.SmallIntegerField(verbose_name='类型', choices=file_type_choices)
    name = models.CharField(verbose_name='文件夹名称', max_length=120, help_text="文件/文件夹名")
    key = models.CharField(verbose_name='文件储存在COS中的KEY', max_length=128, null=True, blank=True)

    # int类型最大表示的数据
    file_size = models.BigIntegerField(verbose_name='文件大小', null=True, blank=True, help_text='字节')

    file_path = models.CharField(verbose_name='文件路径', max_length=255, null=True,
                                 blank=True)  # https://桶.cos.ap-chengdu/....

    parent = models.ForeignKey(verbose_name='父级目录', to='self', related_name='child', null=True, blank=True, on_delete=models.CASCADE)

    update_user = models.ForeignKey(verbose_name='最近更新者', to='UserInfo', null=True, blank=True, on_delete=models.SET_NULL)
    update_datetime = models.DateTimeField(verbose_name='更新时间', auto_now=True)

class Issues(models.Model):
    """ 问题 """
    project = models.ForeignKey(verbose_name='项目', to='Project', on_delete=models.CASCADE)
    issues_type = models.ForeignKey(verbose_name='问题类型', to='IssuesType', on_delete=models.CASCADE)
    module = models.ForeignKey(verbose_name='模块', to='Module', null=True, blank=True, on_delete=models.SET_NULL)

    subject = models.CharField(verbose_name='主题', max_length=80)
    desc = models.TextField(verbose_name='问题描述')
    priority_choices = (
        ("danger", "高"),
        ("warning", "中"),
        ("success", "低"),
    )
    priority = models.CharField(verbose_name='优先级', max_length=12, choices=priority_choices, default='danger')

    # 新建、处理中、已解决、已忽略、待反馈、已关闭、重新打开
    status_choices = (
        (1, '新建'),
        (2, '处理中'),
        (3, '已解决'),
        (4, '已忽略'),
        (5, '待反馈'),
        (6, '已关闭'),
        (7, '重新打开'),
    )
    status = models.SmallIntegerField(verbose_name='状态', choices=status_choices, default=1)

    assign = models.ForeignKey(verbose_name='指派', to='UserInfo', related_name='task', null=True, blank=True, on_delete=models.SET_NULL)
    attention = models.ManyToManyField(verbose_name='关注者', to='UserInfo', related_name='observe', blank=True)

    start_date = models.DateField(verbose_name='开始时间', null=True, blank=True)
    end_date = models.DateField(verbose_name='结束时间', null=True, blank=True)
    mode_choices = (
        (1, '公开模式'),
        (2, '隐私模式'),
    )
    mode = models.SmallIntegerField(verbose_name='模式', choices=mode_choices, default=1)

    parent = models.ForeignKey(verbose_name='父问题', to='self', related_name='child', null=True, blank=True,
                               on_delete=models.SET_NULL)
    require = models.ForeignKey(verbose_name='关联需求', to='AppRequire', null=True, blank=True,
                                on_delete=models.SET_NULL)

    creator = models.ForeignKey(verbose_name='创建者', to='UserInfo', related_name='create_problems', null=True, blank=True, on_delete=models.SET_NULL)

    create_datetime = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    latest_update_datetime = models.DateTimeField(verbose_name='最后更新时间', auto_now=True)

    def __str__(self):
        return self.subject


class Module(models.Model):
    """ 模块 """
    project = models.ForeignKey(verbose_name='项目', to='Project', on_delete=models.CASCADE)
    title = models.CharField(verbose_name='模块名称', max_length=32)

    def __str__(self):
        return self.title


class IssuesType(models.Model):
    """ 问题类型 例如：任务、功能、Bug """

    PROJECT_INIT_LIST = ["代码错误", "设计缺陷", "界面优化", "性能问题", "配置相关", "安装部署", "安全相关", "标准规范", "测试脚本"]

tracer/views.py
import random

import redis
import redis as redis
from django.contrib import auth
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render

from mysite import settings
from tracer.models import UserInfo
from tracer.my_forms import UserForm
from utils.tencent.sms import send_sms_single


def register(request):
    '''
    register view
    '''
    if request.method == 'POST':
        print(request.POST)
        form = UserForm(request.POST)

        response = {'user': None, 'msg': None}
        if form.is_valid():
            telephone = form.cleaned_data.get('telephone')
            code = form.cleaned_data.get('code')
            if code == redis.get(telephone):
                print(form.cleaned_data)
                response['user'] = form.cleaned_data.get('user')
                user = form.cleaned_data.get("user")
                pwd = form.cleaned_data.get('pwd')
                email = form.cleaned_data.get('email')
                telephone = form.cleaned_data.get('telephone')
                avatar_obj = request.FILES.get('avatar')
                extra = {}
                if avatar_obj:
                    extra['avatar'] = avatar_obj

                user_obj = UserInfo.objects.create_user(username=user, password=pwd, email=email, telephone=telephone, **extra)
            else:
                response['msg'] = '请输入正确的验证码'
        else:
            print(form.cleaned_data)
            print(form.errors)
            response['msg'] = form.errors

        return JsonResponse(response)
    form = UserForm()

    return render(request, 'register.html', {'form': form})

def register_valid_code(request):
    telephone = request.POST.get('telephone')
    template_id = settings.TENCENT_SMS_TEMPLATE['register']
    template_param_list = random.randrange(1000, 9999)
    redis.Redis(password="xianjian1998")
    dic = {telephone: template_param_list}
    response = send_sms_single(telephone, template_id, template_param_list=[template_param_list, ])

    return JsonResponse(response)

def get_validCode_img(request):
    '''
    基于PIL模块生成响应状态图片
    '''
    from utils.tracer.valid_code import get_validCode_img
    img_data = get_validCode_img(request)
    return HttpResponse(img_data)

def login(request):
    if request.method == 'POST':

        response = {'user': None, 'msg': None}
        user = request.POST.get("user")
        pwd = request.POST.get('pwd')
        valid_code = request.POST.get('valid_code')

        valid_code_str = request.session.get('valid_code_str')
        if valid_code.upper() == valid_code_str.upper():
            user = auth.authenticate(username=user, password=pwd)
            if user:
                auth.login(request, user)
                response['user'] = user.username
            else:
                response['msg'] = '用户名或密码错误'
        else:
            response['msg'] = '验证码错误'

        return JsonResponse(response)

    return render(request, 'login.html')

tracer/templates/extra_page.html
{% extends 'layout/manage.html' %}

{% block title %}欢迎使用{% endblock %}

{% block css %}
    <style>
        .no-radius {
            border-radius: 0;
            text-align: center;
        }
    </style>
{% endblock %}

{% block content %}

<div class="alert alert-danger no-radius">
    <h4><i class="fa fa-check-circle" aria-hidden="true"></i> 功能尚未开发 </h4>
    <a href="{% url 'project_list' %}">点击跳转至项目列表</a>
</div>
{% endblock %}

tracer/templates/project_detail.html
{% extends 'layout/manage.html' %}
{% load static %}
{% block title %}{{ request.tracer.project.name }}{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static 'plugin/bootstrap-datepicker/css/bootstrap-datepicker.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugin/select2/css/select2.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugin/bootstrap-select/css/bootstrap-select.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugin/select2/css/select2.min.css' %}">

    <style>
        .account {
            width: 1500px;
            margin-top: 30px;
            margin-left: auto;
            margin-right: auto;
            border: 1px solid #f0f0f0;
            padding: 10px 30px 30px 30px;
            -webkit-box-shadow: 5px 10px 10px rgba(0, 0, 0, .05);
            box-shadow: 5px 10px 10px rgba(0, 0, 0, .05);
        }

        .test-result-form {
            text-align: center;
        }
        .form-group {
            margin-left: 10px;
        }
        #form {
            margin-top: 20px;
            text-align: center;
        }
        .pagination {
            float: right;
            margin-top: 10px;
        }
        .platform {
            text-align: center;
        }
        .event-head {
            text-align: center;
        }
        .result {
            width: 80px;
            text-align: center;
        }
        .results-list .version {
            text-align: center;
        }
        .results-list .test-path {
            text-align: center;
        }
        .test_path {
            text-align: left;
        }
        .results-list .task-id {
            text-align: center;
        }
        .results-list .case-url {
            text-align: center;
        }
        .results-list .create-time {
            width: 180px;
            text-align: center;
        }

    </style>
{% endblock %}

{% block content %}
    <form id="form" class="form-inline" role="form">
        {% for field in form %}
            {% if field.name == 'datetime' %}
                <div class="form-group">
                    <label for="{{ field.auto_id }}" class="filter-control">{{ field.label }}</label>
                    <div class="input-group">
                        <span class="input-group-addon" id="sizing-addon2">
                            <i class="fa fa-calendar" aria-hidden="true"></i>
                        </span>
                        {{ field }}
                    </div>
                    <span class="error"></span>
                </div>
            {% else %}
                <div class="form-group">
                    <label for="{{ field.auto_id }}" class="filter-control">{{ field.label }}</label>
                    {{ field }}<span class="error"></span>
                </div>
            {% endif %}
        {% endfor %}
        <input type="button" class="btn btn-success btn-sm"  value="查找" id="search">
    </form>
    <div class="account">
        <div class="test-result-form">
    <table class="table" border="1" style="border-collapse:collapse;">
        <tbody class="results-list">
            <tr class="heard">
                <th class="platform">平台</th>
                <th class="version">版本详情</th>
                <th class="task-id">任务id</th>
                <th class="test-path">脚本路径</th>
                <th class="event-head">EVENT</th>
                <th class="case-url">埋点url</th>
                <th class="th">测试结果</th>
                <th class="create-time">收录时间</th>
            </tr>
        {% for item in issues_object_list %}
            <tr>
                <td class="platform">
                    <div>{{ item.get_platform_display }}</div>
                </td>
                <td class="version">
                    <div>
                        {{ item.version_detail }}
                    </div>
                </td>
                <td class="task_id">
                    <div>{{ item.task_id }}</div>
                </td>
                <td class="test_path">
                    <div>{{ item.test_path }}</div>
                </td>
                <td class="event">
                    <div>{{ item.event }}</div>
                </td>
                <td class="test_case_url">
                        <a href="{{ item.test_case_url }}">
                        {{ item.case_id }}
                        </a>
                </td>
                <td class="result">
                    <div>{{ item.result }}</div>
                </td>
                <td class="create-time">
                    <div>{{ item.create_time|date:"Y年m月d日 H:i" }}</div>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <nav id="page" aria-label="...">
        <ul class="pagination" style="margin-top: 0">
            {{ page_html|safe }}
        </ul>
    </nav>
    </div>
    </div>

{% endblock %}

{% block js %}
    <script src="{% static 'plugin/editor-md/editormd.min.js' %}"></script>
    <script src="{% static 'plugin/bootstrap-datepicker/js/bootstrap-datepicker.min.js' %}"></script>
    <script src="{% static 'plugin/bootstrap-datepicker/locales/bootstrap-datepicker.zh-CN.min.js' %}"></script>
    <script src="{% static 'plugin/bootstrap-select/js/bootstrap-select.min.js' %}"></script>
    <script src="{% static 'plugin/bootstrap-select/js/i18n/defaults-zh_CN.min.js' %}"></script>
    <script src="{% static 'plugin/select2/js/select2.min.js' %}"></script>
    <script src="{% static 'plugin/select2/js/i18n/zh-CN.js' %}"></script>

    <script>
        var RESULT_SEARCH = "{% url 'result_search' project_id=request.tracer.project.id %}";

        $(function () {
            searchClick();
            initDatePicker();
            initDropdown();
        })

        function initDropdown(){
            $('.dropdown-toggle').dropdown();
        }
        /*
        添加对话框：初始化时间选择
         */
        function initDatePicker() {

            $('#id_datetime').datepicker({
                format: 'yyyy-mm-dd',
                {#startDate: '0',#}
                language: "zh-CN",
                autoclose: true
            });
        }

        function searchClick(){
            $('#search').click(function (){
                var platform = $("#id_platform").val()
                var version_detail = $("#id_version_detail").val()
                var task_id = $("#id_task_id").val()
                var test_path = $("#id_test_path").val()
                var event = $("#id_event").val()
                var test_case_url = $("#id_test_case_url").val()
                var create_time = $("#id_datetime").val()
                var result = $("#id_result").val()

                $.ajax({
                    url: RESULT_SEARCH,
                    type: 'GET',
                    data: {
                        "platform": platform,
                        "version_detail": version_detail,
                        "task_id": task_id,
                        "test_path": test_path,
                        "event": event,
                        "test_case_url": test_case_url,
                        "create_time":create_time,
                        "result":result,
                    },
                    success: function (data){
                        console.log('ok')
                        location.href = data.url
                    }
                })
            })
        }
    </script>
{% endblock %}

tracer/templates/setting.html
{% extends 'layout/manage.html' %}
{% load setting %}
{% block content %}
    <div class="container clearfix" style="margin-top: 20px;">
        <div class="col-sm-3">
            {% setting_base_list request %}
        </div>
        <div class="col-sm-9">
            <div class="panel panel-default">
                <div class="panel-heading"><i class="fa fa-address-card-o" aria-hidden="true"></i> 我的资料</div>
                <div class="panel-body">
                    <h4 style="text-align: center;">系统设置</h4>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

tracer/templates/setting_debug.html
{% extends 'layout/manage.html' %}
{% load setting %}
{% load static %}
{% block css %}
    <style>
        .panel-heading i {
            margin-right: 3px;
        }
        .choose {
            border-left: 2px solid #f90 !important;
        }
    </style>
{% endblock %}
{% block content %}
    <div class="container clearfix" style="margin-top: 20px;">
        <div class="col-sm-3">
            {% setting_base_list request %}
        </div>
        <div class="col-sm-9">
            <div class="panel panel-default">
                <div class="panel-heading"><i class="fa fa-keyboard-o" aria-hidden="true"></i>开发者</div>
                <div class="panel-body">
                    <form id="form" class="form-horizontal">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="col-sm-2 control-label">需求或问题标题</label>
                            <div class="col-sm-5">
                                <input type="text" class="form-control" placeholder="请输入标题" id="id_title" name="title">
                                <span class="error">{{ error }}</span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">需求或问题内容</label>
                            <div class="col-sm-5">
                                <div id="editor">
                                    <textarea type="text" class="form-control" placeholder="请输入需求或问题" id="id_content" name="content"></textarea>
                                    <span class="error">{{ error }}</span>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-5">
                                <input type="button" class="btn btn-warning" value="提 交">
                            </div>
                        </div>

                    </form>

                </div>
            </div>

        </div>
    </div>
{% endblock %}

{% block js %}
{#    <script src="{% static 'plugin/editor-md/editormd.min.js' %}"></script>#}

    <script>
        var LOCAL_URL = "{% url 'debug' project_id=request.tracer.project.id %}";
        {#var WIKI_UPLOAD_URL = "{% url 'wiki_upload' project_id=request.tracer.project.id %}";#}

        $(function (){
            submit();
            {#initEditorMd();#}
        })
        function submit(){
            $('.btn').click(function (){
                $('.error').empty();
                $.ajax({
                    url: LOCAL_URL,
                    type: "post",
                    dataType: 'JSON',
                    data: $('#form').serialize(),
                    success: function (data){
                        if(data.status){
                            $('#form').get(0).reset()
                            alert("提交成功，林音已收到")
                        }else {
                            console.log(data.error)
                            $.each(data.error, function (field, error_list) {
                                $("#id_" + field).next().text(error_list[0]);
                            })
                        }
                    }
                })
            })
        }
        {#function initEditorMd() {#}
        {#    editormd('editor',{#}
        {#        placeholder: '请输入内容',#}
        {#        height: 500,#}
        {#        path: '{% static 'plugin/editor-md/lib/' %}',#}
        {#        imageUpload: true,#}
        {#        imageFormats: ["jpg", "jpeg", "png", 'gif'],#}
        {#        imageUploadURL: WIKI_UPLOAD_URL#}
        {#    })#}

    </script>
{% endblock %}